<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0eb65e5f-914b-4212-9373-ada9b71eb266</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\yummy-red-1.0.0\assets\.DS_Store" />
    <None Include="wwwroot\yummy-red-1.0.0\assets\img\.DS_Store" />
    <None Include="wwwroot\yummy-red-1.0.0\assets\vendor\.DS_Store" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
  </ItemGroup>

</Project>
